[build]
  command   = "npm run build"
  publish   = "dist"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = ".netlify/functions-internal"

[[redirects]]
  from   = "/*"
  to     = "/.netlify/functions-internal/server"
  status = 200

